name: Build and Push Latest to Harbor

on:
  push:
    branches: [main, master]
    paths:
      - "main.py"
      - "dump.py"
      - "Dockerfile"
      - "pyproject.toml"
      - "config.ini.sample"
      - "mongodb-database-tools/**"
      - ".github/workflows/build-latest.yml"
  workflow_dispatch: # 允许手动触发

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: izerui/mongo-processor
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo "✅ 镜像已推送到 ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
